# Generated by kpex 0.3.2
crashbackups stop
drc off
gds read /foss/designs/iic-osic-tools/cmos-vco-ihp-sg13g2/design_data/gds/vco.gds
load vco
select top cell
flatten vco_flat
load vco_flat
cellname delete vco -noprompt
cellname rename vco_flat vco
select top cell
extract path /foss/designs/iic-osic-tools/cmos-vco-ihp-sg13g2/design_data/pex/vco__vco/magic_RC
extract do resistance
extract all
ext2sim labels on
ext2sim
extresist tolerance 1
extresist all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice rthresh 100
ext2spice extresist on
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/iic-osic-tools/cmos-vco-ihp-sg13g2/design_data/pex/vco__vco/magic_RC -o /foss/designs/iic-osic-tools/cmos-vco-ihp-sg13g2/design_data/pex/vco__vco/magic_RC/vco.pex.spice
quit -noprompt
